# Generated by Django 5.1.15 on 2026-09-19 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["event_date", "-created_at"],
                "verbose_name": "Actividad",
                "verbose_name_plural": "Actividades",
            },
        ),
        migrations.AddField(
            model_name="event",
            name="activity_type",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="tipo de actividad"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="course",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="curso"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_date",
            field=models.DateField(verbose_name="fecha límite de entrega"),
        ),
    ]
