# Generated by Django 5.1.15 on 2026-09-19 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logistictask",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("in_progress", "En Progreso"),
                    ("completed", "Completada"),
                    ("cancelled", "Cancelada"),
                ],
                default="pending",
                max_length=20,
                verbose_name="estado",
            ),
        ),
    ]
